import { format } from 'date-fns'
import numeral from 'numeral'

export default ({
  eventName,
  attachmentId,
  format: fileFormat,
  size,
  pixel,
  view,
  download,
  length,
  organization,
  createdUser,
  eventCreatedUser,
  updatedOrganization,
  updatedUser,
  updatedTime,
  accessAuthority,
  descName,
  descProjectno,
  descLeader,
  descKeywords,
  descLanguage,
  descPlace,
  descCustomizekeywords,
  downloadAuthority,
  eventId,
  viewUrl,
  hlsUrl,
  video,
  fileRotation,
  fileReason,
}) => {
  const currentTime = format(new Date(), 'yyyy-MM-dd HH:mm:ss')

  return {
    currentTime,
    downloadData: {
      downloadUrl: viewUrl,
      attachmentId,
      organizationId: organization?.orgId,
    },
    viewData: {
      eventName: `${eventName.year}年 ${eventName.name}`,
      attachmentId,
      fileFormat: `${fileFormat}  ${size}  ${pixel}`,
      format: fileFormat,
      viewCount: numeral(view).format('0,0'),
      downloadAuthority,
      downloadCount: numeral(download).format('0,0'),
      fileLength: length,
      deptName: organization?.deptName,
      createdUser: !createdUser && !createdUser ? '無上傳者' : `${createdUser.empName} [員編：${createdUser.empId}]`,
      updatedUser: !updatedUser && !updatedUser ? '無編輯者' : `${updatedOrganization?.deptName} ${updatedUser.empName} [員編：${updatedUser.empId}]`,
      updatedTime: format(new Date(updatedTime), 'yyyy/MM/dd'),
      accessAuthority: Number(accessAuthority),
      description: descName,
      projectNo: descProjectno,
      leader: descLeader.map(item => `${item.user.empName}(${item.user.jobDesc})`).join(' '),
      keywords: descKeywords.map(item => item.itemName).join(' '),
      language: descLanguage?.itemName,
      place: descPlace?.placeNameCh,
      customizekeywords: descCustomizekeywords.map(item => item).join(' '),
      mediaCreatedUserId: createdUser?.empId,
      eventCreatedUserId: eventCreatedUser?.empId,
      viewUrl,
      hlsUrl,
      isVideo: video,
      fileReason,
      eventId,
    },
    editData: {
      attachmentId,
      organizationId: organization?.orgId,
      accessAuthority: String(accessAuthority),
      description: !descName ? '' : descName,
      projectNo: !descProjectno ? '' : descProjectno,
      leader: descLeader.map(value => JSON.stringify(value)),
      keywords: descKeywords.map(item => item.itemId),
      language: descLanguage.itemName,
      place: descPlace?.placeId,
      customizekeywords: descCustomizekeywords,
      fileRotation,
      fileReason: fileReason,
    },
  }
}
